### ISSUE TITLE
Unable to grab Tree View edge to resize it

### ISSUE THREAD

**Issue by adamellsworth** [fgrosjean/acode-ui#2]
![tree-view-grab-bar-thingy-koala](https://user-images.githubusercontent.com/7034617/28232899-10718d74-68a8-11e7-968a-b35245d32247.gif)

- I'm not changing any styles (except for typefaces) in my `styles.less` config.

- I did try restarting the application

- Does not happen with other UI themes (One Light, etc.)

**Comment by fgrosjean** [comment]
I'm trying to replicate your problem but I'm unable... try pasting this to your style.less 
`.atom-dock-resize-handle.left {
  background-color: red;
  width: 5px
}`
That should make visible the resize handler... let me know if that helps

**Comment by adamellsworth** [comment]
sorry for the late response. it works! I removed the color attribute and set the width to 2px which makes it work as expected. thanks for looking into this.
