### ISSUE TITLE
Linenumbers do not follow the line height property set in the Editor settings

### ISSUE THREAD

**Issue by xinix** [fgrosjean/acode-ui#3]
When I increase the line height in the Editor settings, for example to 2.4 the line height of the line numbers  do not follow this setting. 

![atom](https://user-images.githubusercontent.com/606727/28752191-d0bc5b4a-7519-11e7-8455-d3edbbab5681.png)

**Comment by fgrosjean** [comment]
I'm trying to replicate your problem but I'm unable...are you overriding something in your style.less?

**Comment by naicko** [comment]
It seems to be a general issue, non-theme related. As a fix I manually changed the line number size and line height in my style.less to match the ones from the editor. 

Thanks for your reply and this awesome theme. This ticket can be closed.
