### ISSUE TITLE
Acode dark variant

### ISSUE THREAD

**Issue by etherbob** [fgrosjean/acode-ui#4]
I really like the shapes and contrast levels in Acode (relative to itself), but find myself wishing a variant existed in line with some of the darker syntax themes and OS X's own dark mode. I realize this is a significant amount of work, but I wonder: would you ever consider a dark version of the Acode ui?

**Comment by fgrosjean** [comment]
Thanks for using Acode @etherbob, I will consider it in the future... right now I'm focusing on polishing the light theme, new things are coming! hang in there!

**Comment by BenLeggiero** [comment]
Can we reopen this issue? Dark Mode makes more sense now that Mojave has been out for awhile and Catalina is right around the corner.
